name: 'Gitbook Action Build'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - main
      - release/*
  workflow_dispatch:

jobs:
  check-commit-messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Verify commit messages for Signed-off-by tag
      - name: Check commit message signed off by tag
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^Signed-off-by: .+ <.+@.+\..+>$'
          flags: 'g'
          error: 'Commit message must include a Signed-off-by tag in the format: Signed-off-by: Name <email>'
          checkAllCommitMessages: 'true'
          accessToken: ${{secrets.GITBOOK_ACTION_PERSONAL_TOKEN}}
      - name: Check commit message contributed under tag
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^Contributed-under: TianoCore Contribution Agreement 1\.1$'
          flags: 'm'
          error: 'Commit message must include the line: Contributed-under: TianoCore Contribution Agreement 1.1'
          checkAllCommitMessages: 'true'
          accessToken: ${{secrets.GITBOOK_ACTION_PERSONAL_TOKEN}}
  build:
    needs: check-commit-messages
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Get Branch Name
      run: |
        branch=${{github.ref_name}}
        pubdir=${branch/master/draft}
        pubdir=${pubdir/main/draft}
        pubdir=${pubdir////-}
        echo "ON_PUSH_BRANCH_NAME=$branch" >> $GITHUB_ENV
        echo "ON_PUSH_PUBDIR=$pubdir" >> $GITHUB_ENV
    - name: Publish to gh-pages if push
      if: ${{ github.event_name == 'push' }}
      run: |
        echo "ON_PUSH_PUBLISH_BRANCH=gh-pages" >> $GITHUB_ENV
    - name: Publish to pr-pages if not push
      if: ${{ github.event_name != 'push' }}
      run: |
        echo "ON_PUSH_PUBLISH_BRANCH=pr-pages" >> $GITHUB_ENV
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.4
      with:
        token: ${{secrets.GITBOOK_ACTION_PERSONAL_TOKEN}}
        source_branch: ${{env.ON_PUSH_BRANCH_NAME}}
        publish_branch: ${{env.ON_PUSH_PUBLISH_BRANCH}}
        publish_dir: ${{env.ON_PUSH_PUBDIR}}
        publish_remove_last_build: true
        gitbook_pdf: true
        gitbook_pdf_dir: /
        gitbook_pdf_name: ${{ github.event.repository.name }}-${{env.ON_PUSH_PUBDIR}}
        gitbook_epub: true
        gitbook_epub_dir: /
        gitbook_epub_name: ${{ github.event.repository.name }}-${{env.ON_PUSH_PUBDIR}}
        gitbook_mobi: true
        gitbook_mobi_dir: /
        gitbook_mobi_name: ${{ github.event.repository.name }}-${{env.ON_PUSH_PUBDIR}}
